spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: emailsend328@gmail.com
    password: jjqdbhbyudedsfeu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true